config/routes.rb
VideoPush::Application.routes.draw do
  get "tags/index"

  get "pushes/index"

  get "videos/index"

  get 'sign_in' => 'users#new', :as => 'sign_in'
  match 'login' => 'users#login', :as => 'login'
  get 'logout' => 'users#logout', :as => 'logout'
   
  resources :users
  resources :videos do
    resources :pushes
  end
  resources :pushes    
  resources :tags

  root :to => 'pushes#pushes'
  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>VideoPush</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      footer{
        padding-top: 30px;
        text-align: center;  
      }
    </style>
    <%= javascript_include_tag "jquery.min" %>
    <%= yield :head %>
    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand">ST视推</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "首页", root_path  %></li>
                <li><%= link_to "视频", videos_path  %></li>
                <li><%= link_to "推荐", "/path3"  %></li>
                <li><%= link_to "标签", tags_path %></li>
            </ul>
            <form class="navbar-search pull-left"><input type="text" class="search-query" placeholder="Search"></form>
            <p class="navbar-text pull-right">
            <% if session[:user] %>
              Welcome,<%= session[:user].name %> <%= link_to '注销', logout_path %> </p>
            <% else %>
              <%= link_to '注册', new_user_path %> <%= link_to '登陆' %> </p>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <%= yield :library %>
        <div class="row">
          <div class="span9">
            <%= yield %>
          </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                    <li><%= link_to "Link1", "/path1"  %></li>
                    <li><%= link_to "Link2", "/path2"  %></li>
                    <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div>
            </div>
          </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application", :except => "jquery.min" %>
    <script type="text/javascript">
      jQuery(function($){
        var screen = 0;
        $("a.video-down").click(function(){
            var id = $(this).attr('rel');
            $("#image"+id).show();
            $("#myModal"+id).hide();
          });
        $("a.video-up").click(function(){
            var id = $(this).attr('rel');
            $("#image"+id).hide();
            $("#myModal"+id).show();
         });
		//点击外层显示框时 主动focus标签输入框
		$("ul.textboxlist-bits").click(function(){
			$(".textboxlist-bit-editable-input").show();
			$(".textboxlist-bit-editable-input").focus();
      });
		$("ul.textboxlist-bits").live('blur',function(){
			$(".textboxlist-bit-editable-input").hide();
      });
		//输入完成后显示结果
		$(".textboxlist-bit-editable-input").blur(function(){
			var tag = $(".textboxlist-bit-editable-input").val();
			if(tag.length==0)
			return;
			var new_tag = '<li class="textboxlist-bit textboxlist-bit-box textboxlist-bit-box-deletable">';
			new_tag += tag; 
			new_tag += '<a class="textboxlist-bit-box-deletebutton" href="#"></a></li>';
			$(new_tag).insertBefore($(".textboxlist-bit-editable"));
			$(".textboxlist-bit-editable-input").val('');
			init_tag();
      });
		//动态生成的标签中 需要使用live委托事件
		$("a.textboxlist-bit-box-deletebutton").live('click',function(){
			$(this).parent().remove();
      init_tag();
			});
      });
    </script>
  </body>
</html>